//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::{ActiveValue::Set, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "mayiwen", table_name = "title")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(
        column_type = "Text",
        setter = "set_title"  // 指定 setter 方法名（不是函数）
    )]
    pub title: String,
    pub index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// 在 ActiveModel 中实现 setter 方法
impl ActiveModel {
    pub fn set_title(&mut self, title: String) {
        self.title = Set(title.trim().to_string()); // 在这里 trim
    }
}

// 必须实现 ActiveModelBehavior
impl ActiveModelBehavior for ActiveModel {}
