//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use validator::Validate;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "mayiwen", table_name = "login_user")]
// #[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub password: String,
    pub password2: Option<String>,
    pub login_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize, Validate, DeriveIntoActiveModel)]
pub struct LoginUserParams {
    #[validate(length(min = 3, max = 2000, message = "姓名长度为3-2000"))]
    pub name: String,
    #[validate(length(min = 6, max = 2000, message = "姓名长度为6-2000"))]
    pub password: String,
}
