[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app", default-features = false, features = ["ssr"] }
leptos = { workspace = true, features = [ "ssr" ]}
leptos_axum.workspace = true
serde_json = "1.0.145"
anyhow = "1.0.98"
config = { version = "0.15.11", features = ["yaml"] }
validator = { version = "0.20.0", features = ["derive"] }
axum-valid = { version = "0.23.0", features = ["full_validator"] }
xid = "1.1.1"
bytesize = "2.0.1"
regex = "1.11.1"
idgenerator = "2.0.0"
bcrypt = "0.17.0"
jsonwebtoken = "9.3.1"
sea-orm = { version = "1.1.11", features = [
    "with-chrono",
    "debug-print",
    "sqlx-postgres",
    "with-rust_decimal",
    "runtime-tokio",
] }
num_cpus = "1.16.0"
thiserror = "2.0.12"
tracing = { version = "0.1.41", features = ["async-await"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
rust-embed = { version = "8.7.2", features = [
    "axum",
    "axum-ex",
    "tokio",
    "compression",
    "debug-embed",
    "include-exclude",
    "include-flate",
    "interpolate-folder-path",
    "mime-guess",
] }



axum.workspace = true
simple_logger.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
log.workspace = true
